# fly.toml для STAGING версии (тестирование)
app = "entertainment-planner-staging"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  DEBUG = "true"
  ENVIRONMENT = "staging"
  LOG_LEVEL = "DEBUG"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Staging URL будет: https://entertainment-planner-staging.fly.dev