# Canonical dish → inferred cuisine(s). First item = primary.
# Keep keys lower_snake_case; values are canonical cuisine tags used as cuisine:* in tags_csv.

tom_yum: [thai]
tom_kha_gai: [thai]
pad_thai: [thai]
som_tam: [thai_isaan, thai]
larb: [thai_isaan, thai]
nam_tok: [thai_isaan, thai]
massaman_curry: [thai]
green_curry: [thai]
panang_curry: [thai]
khao_soi: [thai_northern, thai]
boat_noodles: [thai]
khao_man_gai: [thai_chinese, thai]
moo_ping: [thai]
pad_krapao: [thai]
mango_sticky_rice: [thai]
khanom_bueng: [thai]
miang_kham: [thai]

ramen: [japanese]
tsukemen: [japanese]
sushi: [japanese]
sashimi: [japanese]
omakase: [japanese]
yakitori: [japanese]
yakisoba: [japanese]
okonomiyaki: [japanese]
tonkatsu: [japanese]
tempura: [japanese]
udon: [japanese]
soba: [japanese]
kaiseki: [japanese]
sukiyaki: [japanese]
shabu_shabu: [japanese]
donburi: [japanese]
gyudon: [japanese]
katsudon: [japanese]
chirashi: [japanese]
takoyaki: [japanese]
taiyaki: [japanese]
japanese_curry: [japanese]
gyoza: [japanese, chinese]

dim_sum: [chinese_cantonese, chinese]
xiao_long_bao: [chinese_shanghai, chinese]
peking_duck: [chinese]
char_siu: [chinese_cantonese, chinese]
wonton_noodles: [chinese_cantonese, chinese]
hot_pot: [chinese]
mala_hot_pot: [chinese_sichuan, chinese]
mapo_tofu: [chinese_sichuan, chinese]
congee: [chinese]
claypot_rice: [chinese_cantonese, chinese]
tea_house_dim_sum: [chinese_cantonese, chinese]
hainanese_chicken_rice: [singaporean, chinese, thai]
chongqing_noodles: [chinese_sichuan, chinese]
jianbing: [chinese]
youtiao: [chinese]

bibimbap: [korean]
tteokbokki: [korean]
korean_fried_chicken: [korean]
bulgogi: [korean]
galbi: [korean]
kimchi_jjigae: [korean]
budae_jjigae: [korean]
samgyeopsal: [korean]
naengmyeon: [korean]
sundubu_jjigae: [korean]
japchae: [korean]

pho: [vietnamese]
bun_cha: [vietnamese]
bun_bo_hue: [vietnamese]
banh_mi: [vietnamese]
goi_cuon: [vietnamese]
bun_rieu: [vietnamese]
ca_phe_trung: [vietnamese]

biryani: [indian]
dosa: [indian_south, indian]
idli: [indian_south, indian]
vada: [indian_south, indian]
butter_chicken: [indian]
tikka_masala: [indian]
rogan_josh: [indian]
palak_paneer: [indian]
naan: [indian]
chaat: [indian]
pani_puri: [indian]
tandoori: [indian]
kathi_roll: [indian]
vindaloo: [indian]
thali: [indian]
prawn_malai_curry: [indian]

laksa: [malaysian, singaporean]
nasi_lemak: [malaysian]
satay: [indonesian, malaysian, thai]
chilli_crab: [singaporean]
kaya_toast: [singaporean]
bak_kut_teh: [malaysian, singaporean]
char_kway_teow: [malaysian, singaporean]

nasi_goreng: [indonesian]
mie_goreng: [indonesian]
rendang: [indonesian]
gado_gado: [indonesian]
soto_ayam: [indonesian]
ayam_penyan: [indonesian]

adobo: [filipino]
lechon: [filipino]
sinigang: [filipino]
halo_halo: [filipino]

shawarma: [middle_eastern]
kebab: [turkish, middle_eastern]
falafel: [middle_eastern]
hummus: [middle_eastern]
tabbouleh: [middle_eastern]
manakish: [levantine, middle_eastern]
kunafa: [middle_eastern]
doner_kebab: [turkish]
lahmacun: [turkish]
pide: [turkish]
menemen: [turkish]

mezze: [middle_eastern, mediterranean]
souvlaki: [greek]
gyros: [greek]
moussaka: [greek]
spanakopita: [greek]

paella: [spanish]
tapas: [spanish]
churros: [spanish]

piri_piri_chicken: [portuguese]
pastel_de_nata: [portuguese]

pizza: [italian]
pasta: [italian]
lasagna: [italian]
risotto: [italian]
carbonara: [italian]
bolognese: [italian]
tiramisu: [italian]
gelato: [italian]
bruschetta: [italian]
gnocchi: [italian]
panini: [italian]

croissant: [french]
baguette_sandwich: [french]
coq_au_vin: [french]
steak_frites: [french]
duck_confit: [french]
bouillabaisse: [french]
creme_brulee: [french]
onion_soup: [french]
patisserie: [french]

burger: [american]
bbq_ribs: [american]
fried_chicken: [american]
mac_and_cheese: [american]
bagel: [american]
cheesecake: [american]
pancakes: [american]
clam_chowder: [american]

tacos: [mexican]
quesadilla: [mexican]
enchiladas: [mexican]
guacamole: [mexican]
elote: [mexican]
pozole: [mexican]
mole: [mexican]

ceviche: [peruvian]
lomo_saltado: [peruvian]
anticuchos: [peruvian]

churrasco: [brazilian]
feijoada: [brazilian]
pao_de_queijo: [brazilian]
brigadeiro: [brazilian]

asado: [argentinian]
empanadas: [argentinian]

injera: [ethiopian]
doro_wat: [ethiopian]

borscht: [ukrainian, russian]
pelmeni: [russian]
varenyky: [ukrainian]

wiener_schnitzel: [austrian]
sachertorte: [austrian]
schnitzel: [german, austrian]
bratwurst: [german]
pretzel: [german]

fish_and_chips: [british]
shepherds_pie: [british]

shawarma_plate: [middle_eastern]
shakshuka: [north_african, middle_eastern]
tagine: [moroccan, north_african]
harira: [moroccan]

bao: [chinese]
roujiamo: [chinese]
dan_dan_noodles: [chinese_sichuan, chinese]
nian_gao_cake: [chinese]
