version: 1
locale: en-TH
updated: 2025-01-21

# Wide slot dictionary for Bangkok.
# Priority: phrase > multiword > unigram > fuzzy (if enabled).
# Canonicals align to existing ontology tags whenever possible.
# For dishes not present in dish:* ontology, we expand to cuisine:* only.

slots:
  # -------------------------
  # CORE VIBES (light set)
  # -------------------------
  - type: vibe
    canonical: chill
    synonyms: [chill, relaxed, calm, low key, laid back, laid-back, easygoing, mellow, unwind]
    expands_to_tags: [vibe:chill]

  - type: vibe
    canonical: romantic
    synonyms: [romantic, romance, date, date night, dating, anniversary, candlelit, intimate, couple friendly, couples, date spot]
    expands_to_tags: [vibe:romantic, scenario:date]

  - type: vibe
    canonical: lively
    synonyms: [lively, energetic, buzzing, vibrant, upbeat]
    expands_to_tags: [vibe:lively]

  - type: vibe
    canonical: cozy
    synonyms: [cozy, snug, homey, warm]
    expands_to_tags: [vibe:cozy]

  - type: vibe
    canonical: premium
    synonyms: [premium, upscale, high end, luxurious, fancy]
    expands_to_tags: [vibe:premium, price:$$$]

  - type: vibe
    canonical: hidden_gem
    synonyms: [hidden gem, secret spot, tucked away, underrated]
    expands_to_tags: [vibe:hidden_gem]

  - type: vibe
    canonical: scenic
    synonyms: [scenic, great view, skyline, sunset view, river view, view, viewpoint, photo spot, instagrammable]
    expands_to_tags: [vibe:scenic, view:skyline]

  - type: vibe
    canonical: instagrammable
    synonyms: [instagrammable, instagram, photo worthy, photogenic, aesthetic]
    expands_to_tags: [vibe:instagrammable]

  # -------------------------
  # EXPERIENCES
  # -------------------------
  - type: experience
    canonical: rooftop
    synonyms: [rooftop, roof top, roof-top, skybar, sky bar, sky-bar, rooftop bar, rooftop restaurant]
    expands_to_tags: [experience:rooftop, view:skyline]

  - type: experience
    canonical: gallery
    synonyms: [gallery, art gallery, exhibition, art exhibit, museum, art space]
    expands_to_tags: [experience:gallery, category:gallery]

  - type: experience
    canonical: spa
    synonyms: [spa, massage, wellness, relaxation, thai massage, luxury spa]
    expands_to_tags: [experience:spa, category:spa]

  - type: experience
    canonical: live_music
    synonyms: [live music, live band, concert, music venue, jazz, blues, acoustic]
    expands_to_tags: [experience:live_music, category:live_music_venue]

  - type: experience
    canonical: park_stroll
    synonyms: [park, stroll, walk, nature, green, botanical garden, garden]
    expands_to_tags: [experience:park_stroll, category:park]

  # -------------------------
  # DRINKS
  # -------------------------
  - type: drink
    canonical: matcha
    synonyms: [matcha, green tea, japanese tea, tea ceremony]
    expands_to_tags: [drink:tea_room, scenario:tea_ceremony]

  - type: drink
    canonical: coffee
    synonyms: [coffee, cafe, specialty coffee, espresso, latte, cappuccino]
    expands_to_tags: [drink:specialty_coffee, category:cafe]

  - type: drink
    canonical: cocktail
    synonyms: [cocktail, cocktail bar, mixology, craft cocktail, signature drink]
    expands_to_tags: [drink:cocktail_bar, category:bar]

  - type: drink
    canonical: wine
    synonyms: [wine, wine bar, natural wine, wine tasting, sommelier]
    expands_to_tags: [drink:wine_bar, category:bar]

  - type: drink
    canonical: craft_beer
    synonyms: [craft beer, beer, brewery, taproom, microbrew, local beer]
    expands_to_tags: [drink:craft_beer, category:bar]

  # -------------------------
  # DISHES
  # -------------------------
  - type: dish
    canonical: tom_yum
    synonyms: [tom yum, tom yam, thai soup, spicy soup, hot and sour soup]
    expands_to_tags: [dish:tom_yum, cuisine:thai]

  - type: dish
    canonical: sushi
    synonyms: [sushi, sashimi, japanese, omakase, nigiri, maki]
    expands_to_tags: [dish:sushi, cuisine:japanese]

  - type: dish
    canonical: pizza
    synonyms: [pizza, italian, margherita, neapolitan, wood fired]
    expands_to_tags: [dish:pizza, cuisine:italian]

  - type: dish
    canonical: pasta
    synonyms: [pasta, spaghetti, carbonara, bolognese, italian]
    expands_to_tags: [dish:pasta, cuisine:italian]

  - type: dish
    canonical: burger
    synonyms: [burger, hamburger, beef burger, gourmet burger]
    expands_to_tags: [dish:burger, category:restaurant]

  # -------------------------
  # CUISINES
  # -------------------------
  - type: cuisine
    canonical: thai
    synonyms: [thai, thailand, thai food, authentic thai, traditional thai]
    expands_to_tags: [cuisine:thai]

  - type: cuisine
    canonical: japanese
    synonyms: [japanese, japan, japanese food, authentic japanese]
    expands_to_tags: [cuisine:japanese]

  - type: cuisine
    canonical: italian
    synonyms: [italian, italy, italian food, authentic italian]
    expands_to_tags: [cuisine:italian]

  - type: cuisine
    canonical: korean
    synonyms: [korean, korea, korean food, korean bbq, authentic korean]
    expands_to_tags: [cuisine:korean]

  - type: cuisine
    canonical: chinese
    synonyms: [chinese, china, chinese food, authentic chinese, cantonese]
    expands_to_tags: [cuisine:chinese]

  # -------------------------
  # AREAS
  # -------------------------
  - type: area
    canonical: sukhumvit
    synonyms: [sukhumvit, sukhumvit road, sukhumvit area]
    expands_to_tags: [area:sukhumvit]

  - type: area
    canonical: silom
    synonyms: [silom, silom road, silom area, business district]
    expands_to_tags: [area:silom]

  - type: area
    canonical: siam
    synonyms: [siam, siam square, siam area, shopping district]
    expands_to_tags: [area:siam]

  - type: area
    canonical: chinatown
    synonyms: [chinatown, yaowarat, chinese quarter]
    expands_to_tags: [area:chinatown]

  - type: area
    canonical: thonglor
    synonyms: [thonglor, thong lo, thonglor area, trendy area]
    expands_to_tags: [area:thonglor]