# fly.toml для STAGING версии (тестирование)
app = "entertainment-planner-staging"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  DEBUG = "false"
  ENVIRONMENT = "staging"
  LOG_LEVEL = "INFO"
  # Feature flags
  SLOTTER_WIDE = "on"
  SLOTTER_SHADOW = "off"
  SLOTTER_DEBUG = "on"
  SLOTTER_AB_TEST = "off"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Staging URL: https://entertainment-planner-staging.fly.dev
