"""add_summary_source_and_version_fields

Revision ID: 33b21fd4d800
Revises: 2b90f17b5877
Create Date: 2025-09-06 13:21:39.441404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b21fd4d800'
down_revision: Union[str, Sequence[str], None] = '2b90f17b5877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('summary_source', sa.Text(), nullable=True))
    op.add_column('places', sa.Column('summary_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'summary_version')
    op.drop_column('places', 'summary_source')
    op.create_table('fts_places_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fts_places_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fts_places_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('fts_places_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('fts_places',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('tags_csv', sa.NullType(), nullable=True),
    sa.Column('summary', sa.NullType(), nullable=True),
    sa.Column('category', sa.NullType(), nullable=True),
    sa.Column('description_full', sa.NullType(), nullable=True),
    sa.Column('address', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
