"""Add bitset fields for Netflix-style search

Revision ID: 64c7b2d304ed
Revises: f8912301f0c0
Create Date: 2025-09-13 14:24:59.871178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c7b2d304ed'
down_revision: Union[str, Sequence[str], None] = 'f8912301f0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add new columns, don't drop FTS5 tables
    op.add_column('places', sa.Column('tag_bitset', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('sig_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'sig_hash')
    op.drop_column('places', 'category_id')
    op.drop_column('places', 'tag_bitset')
    # ### end Alembic commands ###
