"""Add picture_url field to places table

Revision ID: b6c14ba5fd1c
Revises: 73198f3c175d
Create Date: 2025-09-05 14:10:41.054330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c14ba5fd1c'
down_revision: Union[str, Sequence[str], None] = '73198f3c175d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('picture_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'picture_url')
    # ### end Alembic commands ###
