"""add_website_and_phone_fields

Revision ID: f8912301f0c0
Revises: c31814682c27
Create Date: 2025-09-12 15:40:51.891774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8912301f0c0'
down_revision: Union[str, Sequence[str], None] = 'c31814682c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('website', sa.Text(), nullable=True))
    op.add_column('places', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'phone')
    op.drop_column('places', 'website')
    # ### end Alembic commands ###
